version = 0.1
[default]

[default.deploy]

[default.deploy.parameters]
stack_name = "cci-money-exchange"
s3_bucket = "cci-money-exchange"
s3_prefix = "default"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
