version = 0.1
[default]

[default.deploy]

[default.deploy.parameters]
stack_name = "cci-money-exchange"
s3_bucket = "cci-money-exchange"
s3_prefix = "cci-money-exchange"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["MoneyExchangeFunction=709967797311.dkr.ecr.ap-northeast-1.amazonaws.com/sam-repos/moneyexchangefunction"]