version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-pkgfmt-container-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5pdub1hrebwl"
s3_prefix = "lambda-pkgfmt-container-test"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=709967797311.dkr.ecr.ap-northeast-1.amazonaws.com/lambdapkgfmtcontainertest1b7301f0/helloworldfunction19d43fc4repo"]
