version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0

jobs:
  create_repo:
    executor: aws-ecr/default
    steps:
      - aws-ecr/create-repo:
          repo: money_exchange
  prepare_work_image:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          create-repo: true
          dockerfile: ~/.circleci/Dockerfile
          remote-docker-layer-caching: true
          repo: node_with_sam_cli

workflows:
  main:
    jobs:
      - create_repo:
          context: 
            - aws
            - docker
      - prepare_work_image:
          context:
            - aws
            - docker
