version: 2.1

parameters:
  update-work-image:
    type: boolean
    default: false

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  aws-ecr: circleci/aws-ecr@7.2.0
  aws-sam: circleci/aws-sam-serverless@3.1.0

jobs:
  install_aws_cli:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          profile-name: default
      - persist_to_workspace:
          root: ~/
          paths:
            - .aws/*
  create_repo:
    executor: aws-ecr/default
    steps:
      - attach_workspace:
          at: ~/
      - aws-ecr/create-repo:
          repo: money_exchange
  prepare_work_image:
    executor: aws-ecr/default
    steps:
      - attach_workspace:
          at: ~/
      - aws-ecr/build-and-push-image:
          account-url: MY_US_EAST_1_ECR
          attach-workspace: true
          create-repo: true
          docker-login: true
          path: ./.circleci
          region: AWS_US_EAST_1_REGION
          remote-docker-layer-caching: true
          repo: node_with_sam_cli
  build_api:
    executor: aws-sam/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - aws-sam/install
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          command: |
            npm install
      - save_cache:
          key: v1-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - aws-sam/build:
          template: template.yaml
          use-container: true
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.aws-sam

workflows:
  preparation:
    when: << pipeline.parameters.update-work-image >>
    jobs:
      - install_aws_cli:
          context: aws
      - prepare_work_image:
          context:
            - aws
            - docker
          requires:
            - install_aws_cli
      - create_repo:
          context: 
            - aws
            - docker
          requires:
            - install_aws_cli
  main:
    when:
      not: << pipeline.parameters.update-work-image >>
    jobs:
      - build_api:
          context: aws
