version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  aws-ecr: circleci/aws-ecr@7.2.0

jobs:
  install_aws_cli:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          profile-name: default
      - persist_to_workspace:
          root: ~/
          paths:
            - .aws/*
  create_repo:
    executor: aws-ecr/default
    steps:
      - attach_workspace:
          at: ~/
      - aws-ecr/create-repo:
          repo: money_exchange
  prepare_work_image:
    executor: aws-ecr/default
    steps:
      - attach_workspace:
          at: ~/
      - aws-ecr/build-and-push-image:
          account-url: MY_US_EAST_1_ECR
          attach-workspace: true
          create-repo: true
          docker-login: true
          path: ./.circleci
          region: AWS_US_EAST_1_REGION
          remote-docker-layer-caching: true
          repo: node_with_sam_cli
  hello:
    docker:
      - image: 709967797311.dkr.ecr.us-east-1.amazonaws.com/node_with_sam_cli/node_with_sam_cli:latest
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          command: echo hello world

workflows:
  main:
    jobs:
      - install_aws_cli:
          context: aws
      - create_repo:
          context: 
            - aws
            - docker
          requires:
            - install_aws_cli
      - prepare_work_image:
          context:
            - aws
            - docker
          requires:
            - install_aws_cli
      - hello:
          context: aws
          requires:
            - prepare_work_image
