version: 2.1

parameters:
  update-work-image:
    type: boolean
    default: false

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  aws-ecr: circleci/aws-ecr@7.2.0
  aws-sam: circleci/aws-sam-serverless@3.1.0

jobs:
  create_repo:
    executor: aws-ecr/default
    steps:
      - attach_workspace:
          at: ~/
      - aws-ecr/create-repo:
          repo: money_exchange
  build_api:
    docker:
      - image: cimg/python:3.10-node
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - aws-sam/install
      - run:
          command: |
            cd ./money-exchange
            npm install
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-sam/build:
          template: template.yaml
          use-container: true
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.aws-sam
            - project/money-exchange/node_modules
  test_api:
    docker:
      - image: cimg/python:3.10-node
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - aws-sam/install
      - run:
          command: |
            cd ./money-exchange
            npm install
            mkdir reports
            npx nyc npx mocha ./tests/*.test.js --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ./reports/mocha/test-results.xml
      - store_test_results:
          path: ./money-exchange/reports        
  deploy_api:
    docker:
      - image: cimg/python:3.10-node
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - aws-sam/install
      - aws-sam/deploy:
          debug: true
          stack-name: cci-money-exchange
          image-repositories: 709967797311.dkr.ecr.ap-northeast-1.amazonaws.com/cci-money-exchange

workflows:
  main:
    when:
      not: << pipeline.parameters.update-work-image >>
    jobs:
      - build_api:
          context: aws
      - test_api:
          context: aws
          requires:
            - build_api
      - deploy_api:
          context: aws
          requires:
            - test_api
